[package]
name = "resumake"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4"
serde = { version = "1", features = ["derive"] }

[dev-dependencies]
serde_yaml = "0.9"
pretty_assertions = "1.3"
