[package]
name = "resumake"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4"
clap = { version = "4", features = ["derive"] }
serde = { version = "1", features = ["derive"] }
handlebars = "4"
regex = "1"
serde_yaml = "0.9"

[dev-dependencies]
pretty_assertions = "1.3"
